apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: analytics-service-secret
  namespace: togglemaster
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: analytics-service-secret
    creationPolicy: Owner
  data:
    - secretKey: AWS_REGION
      remoteRef:
        key: togglemaster/dev/analytics-service
        property: AWS_REGION
    - secretKey: AWS_SQS_URL
      remoteRef:
        key: togglemaster/dev/analytics-service
        property: AWS_SQS_URL
    - secretKey: AWS_DYNAMODB_TABLE
      remoteRef:
        key: togglemaster/dev/analytics-service
        property: AWS_DYNAMODB_TABLE
