{
 "title": "ToggleMaster - Overview",
 "tags": [
  "togglemaster",
  "fiap",
  "fase4"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Pods Running - ToggleMaster",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=\"togglemaster\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pods com Restart",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"togglemaster\"})"
    }
   ]
  },
  {
   "title": "CPU por Pod",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"togglemaster\", container!=\"\"}[5m])) by (pod)"
    }
   ]
  },
  {
   "title": "Memória por Pod",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 4, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"togglemaster\", container!=\"\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Status dos Pods",
   "type": "table",
   "gridPos": { "x": 0, "y": 12, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{namespace=\"togglemaster\"}"
    }
   ]
  }
 ]
}