apiVersion: batch/v1
kind: Job
metadata:
  name: auth-db-init
  namespace: togglemaster
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: postgres-client
          image: postgres:16
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: DATABASE_URL
          command:
            - /bin/sh
            - -c
            - |
              psql "$DATABASE_URL" -f /sql/init.sql
          volumeMounts:
            - name: init-sql
              mountPath: /sql
      volumes:
        - name: init-sql
          configMap:
            name: auth-db-init-sql