apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-service-secret
  namespace: togglemaster
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: auth-service-secret
    creationPolicy: Owner
  data:
    - secretKey: MASTER_KEY
      remoteRef:
        key: togglemaster/dev/auth-service
        property: MASTER_KEY
    - secretKey: DATABASE_URL
      remoteRef:
        key: togglemaster/dev/auth-service
        property: DATABASE_URL
