apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: evaluation-service-secret
  namespace: togglemaster
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: evaluation-service-secret
    creationPolicy: Owner
  data:
    - secretKey: REDIS_URL
      remoteRef:
        key: togglemaster/dev/evaluation-service
        property: REDIS_URL
    - secretKey: AWS_SQS_URL
      remoteRef:
        key: togglemaster/dev/evaluation-service
        property: AWS_SQS_URL
    - secretKey: FLAG_SERVICE_URL
      remoteRef:
        key: togglemaster/dev/evaluation-service
        property: FLAG_SERVICE_URL
    - secretKey: TARGETING_SERVICE_URL
      remoteRef:
        key: togglemaster/dev/evaluation-service
        property: TARGETING_SERVICE_URL
    - secretKey: SERVICE_API_KEY
      remoteRef:
        key: togglemaster/dev/evaluation-service
        property: SERVICE_API_KEY